// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InternalProtos.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpc.NET40.InternalProtos {

  /// <summary>Holder for reflection information generated from InternalProtos.proto</summary>
  public static partial class InternalProtosReflection {

    #region Descriptor
    /// <summary>File descriptor for InternalProtos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InternalProtosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRJbnRlcm5hbFByb3Rvcy5wcm90bxIZR3JwYy5ORVQ0MC5JbnRlcm5hbFBy",
            "b3RvcyJJChFScGNFeGNlcHRpb25Qcm90bxITCgtzdGF0dXNfY29kZRgBIAEo",
            "BRIOCgZkZXRhaWwYAiABKAkSDwoHbWVzc2FnZRgDIAEoCSIqCgxQYXlsb2Fk",
            "UHJvdG8SDAoEc2l6ZRgBIAEoBRIMCgRkYXRhGAIgASgMItIBCgtQYWNrZXRQ",
            "cm90bxIOCgZtc2dfaWQYASABKAUSFgoORnVsbE1ldGhvZE5hbWUYAiABKAkS",
            "DwoHb3B0aW9ucxgDIAEoBRI6CgdwYXlsb2FkGAQgASgLMicuR3JwYy5ORVQ0",
            "MC5JbnRlcm5hbFByb3Rvcy5QYXlsb2FkUHJvdG9IABJBCglleGNlcHRpb24Y",
            "BSABKAsyLC5HcnBjLk5FVDQwLkludGVybmFsUHJvdG9zLlJwY0V4Y2VwdGlv",
            "blByb3RvSABCCwoJZGF0YV90eXBlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.NET40.InternalProtos.RpcExceptionProto), global::Grpc.NET40.InternalProtos.RpcExceptionProto.Parser, new[]{ "StatusCode", "Detail", "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.NET40.InternalProtos.PayloadProto), global::Grpc.NET40.InternalProtos.PayloadProto.Parser, new[]{ "Size", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpc.NET40.InternalProtos.PacketProto), global::Grpc.NET40.InternalProtos.PacketProto.Parser, new[]{ "MsgId", "FullMethodName", "Options", "Payload", "Exception" }, new[]{ "DataType" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RpcExceptionProto : pb::IMessage<RpcExceptionProto> {
    private static readonly pb::MessageParser<RpcExceptionProto> _parser = new pb::MessageParser<RpcExceptionProto>(() => new RpcExceptionProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RpcExceptionProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.NET40.InternalProtos.InternalProtosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcExceptionProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcExceptionProto(RpcExceptionProto other) : this() {
      statusCode_ = other.statusCode_;
      detail_ = other.detail_;
      message_ = other.message_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RpcExceptionProto Clone() {
      return new RpcExceptionProto(this);
    }

    /// <summary>Field number for the "status_code" field.</summary>
    public const int StatusCodeFieldNumber = 1;
    private int statusCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StatusCode {
      get { return statusCode_; }
      set {
        statusCode_ = value;
      }
    }

    /// <summary>Field number for the "detail" field.</summary>
    public const int DetailFieldNumber = 2;
    private string detail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Detail {
      get { return detail_; }
      set {
        detail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RpcExceptionProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RpcExceptionProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StatusCode != other.StatusCode) return false;
      if (Detail != other.Detail) return false;
      if (Message != other.Message) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StatusCode != 0) hash ^= StatusCode.GetHashCode();
      if (Detail.Length != 0) hash ^= Detail.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StatusCode != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StatusCode);
      }
      if (Detail.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Detail);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StatusCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StatusCode);
      }
      if (Detail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Detail);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RpcExceptionProto other) {
      if (other == null) {
        return;
      }
      if (other.StatusCode != 0) {
        StatusCode = other.StatusCode;
      }
      if (other.Detail.Length != 0) {
        Detail = other.Detail;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            StatusCode = input.ReadInt32();
            break;
          }
          case 18: {
            Detail = input.ReadString();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PayloadProto : pb::IMessage<PayloadProto> {
    private static readonly pb::MessageParser<PayloadProto> _parser = new pb::MessageParser<PayloadProto>(() => new PayloadProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PayloadProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.NET40.InternalProtos.InternalProtosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadProto(PayloadProto other) : this() {
      size_ = other.size_;
      data_ = other.data_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadProto Clone() {
      return new PayloadProto(this);
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 1;
    private int size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PayloadProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PayloadProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Size != other.Size) return false;
      if (Data != other.Data) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Size != 0) hash ^= Size.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Size != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Size);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Size != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Size);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PayloadProto other) {
      if (other == null) {
        return;
      }
      if (other.Size != 0) {
        Size = other.Size;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Size = input.ReadInt32();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PacketProto : pb::IMessage<PacketProto> {
    private static readonly pb::MessageParser<PacketProto> _parser = new pb::MessageParser<PacketProto>(() => new PacketProto());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PacketProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpc.NET40.InternalProtos.InternalProtosReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketProto(PacketProto other) : this() {
      msgId_ = other.msgId_;
      fullMethodName_ = other.fullMethodName_;
      options_ = other.options_;
      switch (other.DataTypeCase) {
        case DataTypeOneofCase.Payload:
          Payload = other.Payload.Clone();
          break;
        case DataTypeOneofCase.Exception:
          Exception = other.Exception.Clone();
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketProto Clone() {
      return new PacketProto(this);
    }

    /// <summary>Field number for the "msg_id" field.</summary>
    public const int MsgIdFieldNumber = 1;
    private int msgId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MsgId {
      get { return msgId_; }
      set {
        msgId_ = value;
      }
    }

    /// <summary>Field number for the "FullMethodName" field.</summary>
    public const int FullMethodNameFieldNumber = 2;
    private string fullMethodName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FullMethodName {
      get { return fullMethodName_; }
      set {
        fullMethodName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "options" field.</summary>
    public const int OptionsFieldNumber = 3;
    private int options_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Options {
      get { return options_; }
      set {
        options_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grpc.NET40.InternalProtos.PayloadProto Payload {
      get { return dataTypeCase_ == DataTypeOneofCase.Payload ? (global::Grpc.NET40.InternalProtos.PayloadProto) dataType_ : null; }
      set {
        dataType_ = value;
        dataTypeCase_ = value == null ? DataTypeOneofCase.None : DataTypeOneofCase.Payload;
      }
    }

    /// <summary>Field number for the "exception" field.</summary>
    public const int ExceptionFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Grpc.NET40.InternalProtos.RpcExceptionProto Exception {
      get { return dataTypeCase_ == DataTypeOneofCase.Exception ? (global::Grpc.NET40.InternalProtos.RpcExceptionProto) dataType_ : null; }
      set {
        dataType_ = value;
        dataTypeCase_ = value == null ? DataTypeOneofCase.None : DataTypeOneofCase.Exception;
      }
    }

    private object dataType_;
    /// <summary>Enum of possible cases for the "data_type" oneof.</summary>
    public enum DataTypeOneofCase {
      None = 0,
      Payload = 4,
      Exception = 5,
    }
    private DataTypeOneofCase dataTypeCase_ = DataTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataTypeOneofCase DataTypeCase {
      get { return dataTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDataType() {
      dataTypeCase_ = DataTypeOneofCase.None;
      dataType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PacketProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PacketProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgId != other.MsgId) return false;
      if (FullMethodName != other.FullMethodName) return false;
      if (Options != other.Options) return false;
      if (!object.Equals(Payload, other.Payload)) return false;
      if (!object.Equals(Exception, other.Exception)) return false;
      if (DataTypeCase != other.DataTypeCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgId != 0) hash ^= MsgId.GetHashCode();
      if (FullMethodName.Length != 0) hash ^= FullMethodName.GetHashCode();
      if (Options != 0) hash ^= Options.GetHashCode();
      if (dataTypeCase_ == DataTypeOneofCase.Payload) hash ^= Payload.GetHashCode();
      if (dataTypeCase_ == DataTypeOneofCase.Exception) hash ^= Exception.GetHashCode();
      hash ^= (int) dataTypeCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MsgId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MsgId);
      }
      if (FullMethodName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FullMethodName);
      }
      if (Options != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Options);
      }
      if (dataTypeCase_ == DataTypeOneofCase.Payload) {
        output.WriteRawTag(34);
        output.WriteMessage(Payload);
      }
      if (dataTypeCase_ == DataTypeOneofCase.Exception) {
        output.WriteRawTag(42);
        output.WriteMessage(Exception);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MsgId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MsgId);
      }
      if (FullMethodName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FullMethodName);
      }
      if (Options != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Options);
      }
      if (dataTypeCase_ == DataTypeOneofCase.Payload) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      if (dataTypeCase_ == DataTypeOneofCase.Exception) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Exception);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PacketProto other) {
      if (other == null) {
        return;
      }
      if (other.MsgId != 0) {
        MsgId = other.MsgId;
      }
      if (other.FullMethodName.Length != 0) {
        FullMethodName = other.FullMethodName;
      }
      if (other.Options != 0) {
        Options = other.Options;
      }
      switch (other.DataTypeCase) {
        case DataTypeOneofCase.Payload:
          Payload = other.Payload;
          break;
        case DataTypeOneofCase.Exception:
          Exception = other.Exception;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MsgId = input.ReadInt32();
            break;
          }
          case 18: {
            FullMethodName = input.ReadString();
            break;
          }
          case 24: {
            Options = input.ReadInt32();
            break;
          }
          case 34: {
            global::Grpc.NET40.InternalProtos.PayloadProto subBuilder = new global::Grpc.NET40.InternalProtos.PayloadProto();
            if (dataTypeCase_ == DataTypeOneofCase.Payload) {
              subBuilder.MergeFrom(Payload);
            }
            input.ReadMessage(subBuilder);
            Payload = subBuilder;
            break;
          }
          case 42: {
            global::Grpc.NET40.InternalProtos.RpcExceptionProto subBuilder = new global::Grpc.NET40.InternalProtos.RpcExceptionProto();
            if (dataTypeCase_ == DataTypeOneofCase.Exception) {
              subBuilder.MergeFrom(Exception);
            }
            input.ReadMessage(subBuilder);
            Exception = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
