/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SearchResult : TBase
{
  private bool _Found;
  private string _FileName;

  public bool Found
  {
    get
    {
      return _Found;
    }
    set
    {
      __isset.Found = true;
      this._Found = value;
    }
  }

  public string FileName
  {
    get
    {
      return _FileName;
    }
    set
    {
      __isset.FileName = true;
      this._FileName = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool Found;
    public bool FileName;
  }

  public SearchResult() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Bool) {
            Found = iprot.ReadBool();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            FileName = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("SearchResult");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.Found) {
      field.Name = "Found";
      field.Type = TType.Bool;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteBool(Found);
      oprot.WriteFieldEnd();
    }
    if (FileName != null && __isset.FileName) {
      field.Name = "FileName";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(FileName);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("SearchResult(");
    sb.Append("Found: ");
    sb.Append(Found);
    sb.Append(",FileName: ");
    sb.Append(FileName);
    sb.Append(")");
    return sb.ToString();
  }

}

